name: real_state
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_bloc: ^9.1.0
  shared_preferences: ^2.5.3
  flutter_svg: ^2.1.0
  intl: ^0.20.2
  intl_phone_number_input: ^0.7.4
  dartz: ^0.10.1
  logger: ^2.5.0
  dio: ^5.8.0+1
  go_router: ^16.0.0
  get_it: ^8.0.3
  injectable: ^2.5.0
  retrofit: ^4.4.2
  json_annotation: ^4.9.0
  cached_network_image: ^3.4.1
  http_parser: ^4.1.2
  carousel_slider: ^5.0.0
  image_picker: ^1.1.2
  file_picker: ^10.1.2
  firebase_core: ^3.13.0
  firebase_messaging: ^15.2.5
  url_launcher: ^6.3.1
  #  google_maps_flutter: ^2.12.1
  google_maps_flutter: ^2.12.3
  map_launcher: ^3.5.0
  image_cropper: ^9.1.0
  hive_flutter: ^1.1.0
  hydrated_bloc: ^10.1.1
  path_provider: ^2.1.5
  photo_view: ^0.15.0
  flutter_launcher_icons: ^0.14.4
  google_maps_cluster_manager_2: ^3.2.0
  platform_identity:
    git: https://github.com/SalemZakkar/platform_identity.git



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  json_serializable: ^6.9.5
  build_runner: ^2.4.15
  flutter_gen: ^5.10.0
  injectable_generator: ^2.7.0
  flutter_gen_runner: ^5.10.0
  retrofit_generator: ^9.1.9
  flutter_native_splash: ^2.4.6


flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/icons/
    - assets/font/
    - assets/images/
    - assets/maps/

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/font/Cairo-ExtraLight.ttf
          weight: 200
        - asset: assets/font/Cairo-Light.ttf
          weight: 300
        - asset: assets/font/Cairo-Regular.ttf
          weight: 400
        - asset: assets/font/Cairo-Medium.ttf
          weight: 500
        - asset: assets/font/Cairo-SemiBold.ttf
          weight: 600
        - asset: assets/font/Cairo-Bold.ttf
          weight: 700
        - asset: assets/font/Cairo-ExtraBold.ttf
          weight: 800
        - asset: assets/font/Cairo-Black.ttf
          weight: 900
    - family: Manrope
      fonts:
        - asset: assets/font/Manrope-ExtraLight.ttf
          weight: 200
        - asset: assets/font/Manrope-Light.ttf
          weight: 300
        - asset: assets/font/Manrope-Regular.ttf
          weight: 400
        - asset: assets/font/Manrope-Medium.ttf
          weight: 500
        - asset: assets/font/Manrope-SemiBold.ttf
          weight: 600
        - asset: assets/font/Manrope-Bold.ttf
          weight: 700
        - asset: assets/font/Manrope-ExtraBold.ttf
          weight: 800


flutter_gen:
  output: lib/generated/generated_assets/
  integrations:
    flutter_svg: true